### ISSUE TITLE
VBS Obfuscator

### ISSUE THREAD

**Issue by redespace** [st0le/st0le#1]
Hi St0le,

I desperately need assistance trying to defuscate a VBS a wrote many years ago. I used your code from stackoverflow:

```
'VBS Obfuscator by st0le

Randomize
set fso = CreateObject("Scripting.FileSystemObject")
fileName = Inputbox("Enter Path of the File to scramble : ")
set src = fso.OpenTextfile(fileName,1)
body = src.readall
set rep  = fso.createtextfile("Obfuscated.vbs",true)
rep.writeline "Execute(" & Obfuscate(body) & " ) "

Function Obfuscate(txt)
enc = ""
for i = 1 to len(txt)
enc = enc & "chr( " & form( asc(mid(txt,i,1)) ) & " ) & "
next
Obfuscate = enc & " vbcrlf "
End Function


Function form(n)

r = int(rnd * 10000)
k = int(rnd * 3)
if( k = 0) then ret = (r+n) & "-" & r
if( k = 1) then ret = (n-r) & "+" & r
if( k = 2) then ret = (n*r) & "/" & r
form = ret
End Function
```

There used to be an online defuscator but is not online anymore. Is there a way you can help me revert it?
Thank you

**Comment by st0le** [comment]
Simplest way.
1) Replace "Execute" with "Msgbox". 
2) Run the file, It will popup a message box with the Source Code. Don't close the msgbox yet.
3) Press Ctrl+C. Paste into notepad.

Remove the Hyphen lines and the OK at the end.
